/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ExampleExternalContractInterface extends utils.Interface {
  contractName: "ExampleExternalContract";
  functions: {
    "complete()": FunctionFragment;
    "completed()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "complete", values?: undefined): string;
  encodeFunctionData(functionFragment: "completed", values?: undefined): string;

  decodeFunctionResult(functionFragment: "complete", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "completed", data: BytesLike): Result;

  events: {};
}

export interface ExampleExternalContract extends BaseContract {
  contractName: "ExampleExternalContract";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ExampleExternalContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    complete(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    completed(overrides?: CallOverrides): Promise<[boolean]>;
  };

  complete(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  completed(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    complete(overrides?: CallOverrides): Promise<void>;

    completed(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    complete(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    completed(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    complete(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    completed(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
